### ISSUE TITLE
The consumer subscribes only to the first topic entered

### ISSUE THREAD

**Issue by zulimazuli** [glazkovalex/Rebus.Kafka#9] opened 2023-12-07 14:45 UTC
Hi, I use Rebus for integration events. I have to switch to Kafka for some reason and wanted to use this library. 
Unfortunately, I have encountered a problem.

By adding more topics, the consumer subscribes only to the first one,
so that, although many topics are sent, only one is received (subscribed to).

The current setup works flawless for RabbitMQ or InMemory transport implementations.

I suspect that the issue may be related to topic subscription.

I have reproduced the issue on your example:

#### Steps to reproduce:
Using the Examples projects available: `Scaleout.Producer`, `Scaleout.Messages` and `Scaleout.Consumers`, 
I modified the Producer and Consumers project as follows:
* I added `TestMessage2` (a copy of TestMessge).
* I added `TestMessageHandler2 : IHandleMessages<TestMessage2>` (copy of TestMessageHandler).
* I registered the new handler (Consumers).
* I added Rebus Routing for Assembly `TestMessage2` (Producer and Consumers).
* I subscribed to both topics: (Consumers)
`bus.Subscribe<TestMessage>().Wait();`
`bus.Subscribe<TestMessage2>().Wait();`
* I published messages from both TestMessage and TestMessage2 to the do-while loop in Producer.

_Expected behaviour:_
Console outputs messages from both topics.

_Actual:_
Console outputs only topics from TestMessage.

Any idea what could be the cause, or maybe I'm doing something wrong?

**Comment by glazkovalex** [comment] 2023-12-09 17:00
> Hi, I use Rebus for integration events. I have to switch to Kafka for some reason and wanted to use this library. Unfortunately, I have encountered a problem.
> ...

Thank you for the information about the bug! 
Tomorrow I will try to reproduce it and fix it.

**Comment by glazkovalex** [comment] 2023-12-10 16:58
@zulimazuli , hello!
I couldn't reproduce the bug :( 
But I added test [TwoPublishTwoSubscribe](https://github.com/glazkovalex/Rebus.Kafka/blob/8195b1fd574f529fa7863b72f7214988c441712b/Rebus.Kafka.Tests/SimpleTests.cs#L201), which checks the subscription for two events.
I also adjusted [the example so that it works through two events (topics)](https://github.com/glazkovalex/Rebus.Kafka/commit/8195b1fd574f529fa7863b72f7214988c441712b). 
![result](https://github.com/glazkovalex/Rebus.Kafka/assets/14311620/0ae4dd0e-042a-48f0-9bef-d9ab737f089d)
You can check them on your equipment. Please write to me how the test and example work for you.

**Comment by glazkovalex** [comment] 2023-12-16 11:09
Apparently you've made sure that it's not about the Rebus.Kafka library. Closing the issue.

**Comment by glazkovalex** [comment] 2023-12-16 11:09
Apparently you've made sure that it's not about the Rebus.Kafka library. Closing the issue.

**Closed as completed by glazkovalex** 2023-12-16 11:09 UTC
